name: Update awesome list

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: awesome
        uses: simonecorsi/mawesome@latest
        with:
          api-token: ${{ .env.API_TOKEN }}
